global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  nomad:
    endpoint:
      address: "http://127.0.0.1:4646"
    defaultRule: "Host(`{{ .Name }}.localhost`)"
    exposedByDefault: false
    # Primary provider gets faster refresh
    refreshInterval: "{{ if eq (env \"TRAEFIK_PROVIDER_PRIMARY\") \"nomad\" }}15s{{ else }}30s{{ end }}"
    prefix: "traefik"
    stale: false
    # Enable when primary
    watch: {{ eq (env "TRAEFIK_PROVIDER_PRIMARY") "nomad" }}

  consulCatalog:
    prefix: "traefik"
    exposedByDefault: false
    defaultRule: "Host(`{{ .Name }}.localhost`)"
    endpoint:
      address: "127.0.0.1:8500"
      scheme: "http"
    connectAware: true
    # Primary provider gets faster refresh
    refreshInterval: "{{ if eq (env \"TRAEFIK_PROVIDER_PRIMARY\") \"consul\" }}15s{{ else }}30s{{ end }}"
    # Enable when primary  
    watch: {{ eq (env "TRAEFIK_PROVIDER_PRIMARY") "consul" }}

certificatesResolvers:
  default:
    acme:
      email: "admin@localhost"
      storage: "/pv/CERTS/acme.json"
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  insecure: true

log:
  level: "INFO"
  format: "json"

metrics:
  prometheus: {}
