global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  # Primary provider (Nomad)
  nomad:
    endpoint:
      address: "http://127.0.0.1:4646"
    defaultRule: "Host(`{{ normalize .Name }}.{{ env \"DOMAIN_SUFFIX\" \"localhost\" }}`)"
    exposedByDefault: false
    refreshInterval: "15s"
    prefix: "traefik"
    stale: false
    # Always watch Nomad - it's lightweight and local
    watch: true

  # Secondary provider (Consul)
  consulCatalog:
    prefix: "traefik"
    exposedByDefault: false
    defaultRule: "Host(`{{ normalize .Name }}.{{ env \"DOMAIN_SUFFIX\" \"localhost\" }}`)"
    endpoint:
      address: "127.0.0.1:8500"
      scheme: "http"
    connectAware: true
    refreshInterval: "15s"
    # Always watch Consul - modern hardware can handle it
    watch: true

certificatesResolvers:
  default:
    acme:
      email: "admin@localhost"
      storage: "/pv/CERTS/acme.json"
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  insecure: true

log:
  level: "INFO"
  format: "json"

metrics:
  prometheus: {}
