global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
      middlewares:
        - secure-headers@file
  websecure:
    address: ":443"
    http:
      middlewares:
        - secure-headers@file
    http3:
      advertisedPort: 443
    tls:
      options:
        default:
          minVersion: "VersionTLS12"
          preferServerCipherSuites: true
          cipherSuites:
            - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
            - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305

http:
  middlewares:
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlMaxAge: 100
        addVaryHeader: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: "https"

providers:
  # Primary provider (Nomad)
  nomad:
    endpoint:
      address: "http://127.0.0.1:4646"
    defaultRule: "Host(`{{ normalize .Name }}.{{ index .Tags \"environment\" \"default\" }}.{{ index .Tags \"domain\" (env \"DOMAIN_SUFFIX\" \"localhost\") }}`)"
    exposedByDefault: false
    refreshInterval: "15s"
    prefix: "traefik"
    stale: false
    # Always watch Nomad - it's lightweight and local
    watch: true

  # Secondary provider (Consul)
  consulCatalog:
    prefix: "traefik"
    exposedByDefault: false
    defaultRule: "Host(`{{ normalize .Name }}.{{ index .Meta \"environment\" \"default\" }}.{{ index .Meta \"domain\" (env \"DOMAIN_SUFFIX\" \"localhost\") }}`)"
    endpoint:
      address: "127.0.0.1:8500"
      scheme: "http"
    connectAware: true
    refreshInterval: "15s"
    # Always watch Consul - modern hardware can handle it
    watch: true

certificatesResolvers:
  default:
    acme:
      email: "admin@localhost"
      storage: "/pv/CERTS/acme.json"
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  insecure: true

log:
  level: "INFO"
  format: "json"
  filePath: "/dev/stdout"

accessLog:
  filePath: "/dev/stdout"
  format: "json"
  fields:
    defaultMode: "keep"
    names:
      ClientUsername: "drop"
    headers:
      defaultMode: "keep"
      names:
        User-Agent: "redact"
        Authorization: "drop"
        Cookie: "drop"

metrics:
  prometheus: {}
